# Generated by Django 3.1.1 on 2020-09-13 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='validity',
            new_name='valid',
        ),
    ]
