# Generated by Django 3.0.4 on 2020-09-20 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
